export default {
  LOGIN: 'USER.LOGIN',
  LOGIN_REQUEST: 'USER.LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER.LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER.LOGIN_FAILURE',

  LOGIN_TOKEN: 'USER.LOGIN_TOKEN',
  LOGIN_TOKEN_REQUEST: 'USER.LOGIN_TOKEN_REQUEST',
  LOGIN_TOKEN_SUCCESS: 'USER.LOGIN_TOKEN_SUCCESS',
  LOGIN_TOKEN_FAILURE: 'USER.LOGIN_TOKEN_FAILURE',

  REGISTER: 'USER.REGISTER',
  REGISTER_REQUEST: 'USER.REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER.REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER.REGISTER_FAILURE',

  RESEND_VERIFY: 'USER.RESEND_VERIFY',
  RESEND_VERIFY_REQUEST: 'USER.RESEND_VERIFY_REQUEST',
  RESEND_VERIFY_FAILURE: 'USER.RESEND_VERIFY_FAILURE',

  VERIFY: 'USER.VERIFY',
  VERIFY_REQUEST: 'USER.VERIFY_REQUEST',
  VERIFY_FAILURE: 'USER.VERIFY_FAILURE',

  FORGOT_PASSWORD: 'USER.FORGOT_PASSWORD',
  FORGOT_PASSWORD_REQUEST: 'USER.FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_FAILURE: 'USER.FORGOT_PASSWORD_FAILURE',

  RESET_PASSWORD: 'USER.RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'USER.RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_FAILURE: 'USER.RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD: 'USER.CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'USER.CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_FAILURE: 'USER.CHANGE_PASSWORD_FAILURE',

  EDIT_PROFILE: 'USER.EDIT_PROFILE',
  EDIT_PROFILE_REQUEST: 'USER.EDIT_PROFILE_REQUEST',
  EDIT_PROFILE_FAILURE: 'USER.EDIT_PROFILE_FAILURE',

  BUY: 'PAYMENT.BUY',
  SELL: 'PAYMENT.SELL',
  CONVERT: 'PAYMENT.CONVERT',
  SEND: 'PAYMENT.SEND',
  RECEIVE: 'PAYMENT.RECEIVE',

  BUY_FAILURE: 'PAYMENT.BUY_FAILURE',
  SELL_FAILURE: 'PAYMENT.SELL_FAILURE',
  CONVERT_FAILURE: 'PAYMENT.CONVERT_FAILURE',
  SEND_FAILURE: 'PAYMENT.SEND_FAILURE',
  RECEIVE_FAILURE: 'PAYMENT.RECEIVE_FAILURE',

  BUY_REQUEST: 'PAYMENT.BUY_REQUEST',
  SELL_REQUEST: 'PAYMENT.SELL_REQUEST',
  CONVERT_REQUEST: 'PAYMENT.CONVERT_REQUEST',
  SEND_REQUEST: 'PAYMENT.SEND_REQUEST',
  RECEIVE_REQUEST: 'PAYMENT.RECEIVE_REQUEST',

  HISTORY_LOAD_REQUEST: 'TRANSACTION.LOAD_REQUEST',
  HISTORY_LOAD_FAILURE: 'TRANSACTION.LOAD_FAILURE',
  HISTORY_LOAD: 'TRANSACTION.LOAD',


  SETTING_LOAD: 'SETTING.LOAD',

  SET_PROFILE: 'USER.SET_PROFILE',
  LOGOUT: 'USER.LOGOUT'
}