export default {
  LOGIN: 'USER.LOGIN',
  LOGIN_REQUEST: 'USER.LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER.LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER.LOGIN_FAILURE',

  LOGIN_TOKEN: 'USER.LOGIN_TOKEN',
  LOGIN_TOKEN_REQUEST: 'USER.LOGIN_TOKEN_REQUEST',
  LOGIN_TOKEN_SUCCESS: 'USER.LOGIN_TOKEN_SUCCESS',
  LOGIN_TOKEN_FAILURE: 'USER.LOGIN_TOKEN_FAILURE',

  REGISTER: 'USER.REGISTER',
  REGISTER_REQUEST: 'USER.REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER.REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER.REGISTER_FAILURE',

  BUY: 'PAYMENT.BUY',
  SELL: 'PAYMENT.SELL',
  CONVERT: 'PAYMENT.CONVERT',
  SEND: 'PAYMENT.SEND',
  RECEIVE: 'PAYMENT.RECEIVE',

  SET_PROFILE: 'USER.SET_PROFILE',
  LOGOUT: 'USER.LOGOUT'
}