import React, { useState, useEffect, useRef } from "react";
import { connect } from "react-redux";
import Images from "src/theme/Images";
import * as S from "./styled";

const WhatIsPage = (props) => {
  return (
    <>
        <S.CardContainer>
            <h1>What is Crypto?</h1>
            <h3>Nomismata Capital is one of the easiest and most trusted places to buy Crypto securely</h3>
            <div className="image-container">
                <img className="main-image" src={Images.CirecleBtcIcon} alt="bitcoin"/>
                <img className="sub-image" src={Images.CircleQuestionIcon} alt="question"/>   
            </div>
        </S.CardContainer>
        <S.BasicsContainer>
            <h1>Crypto Basics</h1>
            <p>Crypto is a form of digital currency which is also known as a crypto currency.
                Crypto are digital coins that are designed to be delivered via the internet. Crypto
                are generated by miners who use unique computer software to solve mathematical
                problems and are given a certain number of Crypto in return for their work. Only 21
                million Crypto will ever exist. Currently, around 17 million are in existence. The
                remaining Crypto will become much more difficult to mine as time goes on.
            </p>
        </S.BasicsContainer>
        <S.CryptoWorkContainer>
            <h1>How does Crypto work?</h1>
            <div className="work-wrapper px-3">
                <div className="work-item">
                    <img src={Images.WhiteBtcIcon} alt="bitcoin"/>
                    <p>You can purchase Crypto at an exchange such as
                        Nomismata Capital by creating a free account and using
                        our service to buy the amount of Bitcoin that you
                        wish to buy. In addition to exchanges, Bitcoin may
                        allso be purchased from other individuals.
                    </p>
                </div>
                <div className="work-item">
                    <img src={Images.HandIcon} alt="bitcoin"/>
                    <p>The simplest way to store and use your Crypto is
                        by keeping them in a online digital wallet.
                        However, you can also send them to an external or
                        offline wallet. From your wallet, Crypto can be sent
                        to friends or family and/or to make payments to
                        retailers who accept Crypto.
                    </p>
                </div>
                <div className="work-item">
                    <img src={Images.Card2Icon} alt="bitcoin"/>
                    <p>Crypto transactions differ from credit or debit card
                        purchases. When using Crypto, you don't need to
                        provide a card number, expiration date, name or
                        CVV code. Another advantage is lower
                        transactions fees. Generally, Crypto transactions
                        cost only a fraction of the average 2-3% charged
                        for card transactions.
                    </p>
                </div>
            </div>
            <h2>Crypto also works well as an International currency.<br/>
                Overseas payments can be sent instantly.
            </h2>
        </S.CryptoWorkContainer>
        <S.AdvantageContainer>
            <h1>Bitcoin Advantages</h1>
            <div className="advantage-wrapper">
                <div className="item">
                    <h3>Decentralized Currency</h3>
                    <p>It is possible to transfer Crypto
                        from one person to another no
                        matter where they are located in
                        the world. This can be done
                        without the need for any middle
                        man. All that is required is an
                        internet connection and a Bitcoin
                        wallet address.</p>
                </div>
                <div className="item">
                    <h3>International Currency</h3>
                    <p>Crypto is not linked to any one
                        country and is not bound by
                        borders. It holds the same value
                        in every location, which renders it
                        a much easier overseas payment
                        process.</p>
                </div>
                <div className="item">
                    <h3>Reduced Costs</h3>
                    <p>Without any need to rely on
                        banks or credit card companies,
                        Crypto fees are considerably less
                        than those charged by traditional
                        payment services.</p>
                </div>
                <div className="item">
                    <h3>Eliminate the Bank</h3>
                    <p>Control your Crypto with your
                        own Crypto wallet. Make
                        purchases or send money,
                        bypassing the bank entirely.</p>
                </div>
            </div>
        </S.AdvantageContainer>
    </>
  );
};

const mapStateToProps = state => ({
  
});

const mapDispatchToProps = dispatch => ({
  dispatch,
});

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(WhatIsPage);