export default {
    logo: require('../assets/myImages/logo.png'),
    banner: require('../assets/myImages/banner.png'),
    NFTLogo: require('../assets/myImages/NFT.gif'),
    background: require('../assets/myImages/background.png'),




    LogoWhite: require('../assets/img/HMS-Logo-Red-WHITE-SR19-8R1.png'),
    Facebook: require('../assets/img/Facebook-Icon.svg'),
    PlusAccount: require('../assets/img/panorama.jpg'),
    DiscountAccount: require('../assets/img/bank-note-panorama.jpg'),
    PaymentProcessingApple: require('../assets/img/apple-and-android-logos.png'),
    PaymentProcessingOption: require('../assets/img/tablet_phone_processing.png'),
    PaymentProcessingSolution: require('../assets/img/Devices.png'),
    PaymentProcessingSolution2: require('../assets/img/hand-with-credit-card-above-laptop-keyboard-179016423-1.jpg'),
    endImg:require('../assets/img/young-woman-pay-by-mobile-phone-in-cafe-LY5HM64.jpg'),
    PaymentTopImg: require('../assets/img/young-woman-paying-with-credit-card-in-cafe-H4U3T25.jpg'),
    MerchantServices1: require('../assets/img/Point-of-sale-systems-1-panorama.jpg'),
    MerchantServices2: require('../assets/img/Business-Loans-panorama.jpg'),
    MerchantServices3: require('../assets/img/electronic-payment-concept-18521448-1.jpg'),
    Pricing1:require('../assets/img/Smiling-Business-Owner.jpg'),
    Pricing2:require('../assets/img/Happy-Customer-.jpeg'),
    Pricing3:require('../assets/img/Discounts-For-Large-Purchases.jpg'),
    FundingTimes1: require('../assets/img/website_banner_next_day_funding-1.jpg'),
    FundingTimes2: require('../assets/img/USA-time-zone-map-Batch-Times.jpg'),
    FundingTimes3: require('../assets/img/Days-of-the-week-batch-funding-SR17-8R2.png'),
    FundingTimes4: require('../assets/img/paying-by-credit-card-AEMKGRF.jpg'),
    ECommerceProcessing1: require('../assets/img/website_banner_ecommerce_trends_1.jpg'),
    ECProcessingShpCarts1: require('../assets/img/woocommerce-logo.jpg'),
    ECProcessingShpCarts2: require('../assets/img/Shopify.jpg'),
    ECProcessingShpCarts3: require('../assets/img/Magento.jpg'),
    ECProcessingShpCarts4: require('../assets/img/Big-commerce.jpg'),
    ECProcessingShpCarts5: require('../assets/img/WIX.jpg'),
    ECProcessingShpCarts6: require('../assets/img/3dcart-logo.jpg'),
    ECProcessingShpCarts7: require('../assets/img/Pinnacle-shopping-cart.jpg'),
    ECProcessingShpCarts8: require('../assets/img/xcart-logo.jpg'),
    MobilePaymentProcessing1: require('../assets/img/Mobile-processing-banner-4.jpg'),
    MobilePaymentProcessing2: require('../assets/img/vital-mobile-main.jpg'),
    MobilePaymentProcessing3: require('../assets/img/swipesimpleimage.png'),
    MobilePaymentProcessing4: require('../assets/img/A920-1-2_530x@2x.png'),
    MobilePaymentProcessing5: require('../assets/img/A80.png'),
    MobilePaymentProcessing6: require('../assets/img/Interchange-Plus-VS-Flate-Rate-Infographic_SR18-3R3.jpg'),
    MobilePaymentProcessing7: require('../assets/img/Happy-Casheir-Using-Clover-POS.jpg'),
    VirtualTerminals1: require('../assets/img/CVV-Online-Order.jpg'),
    VirtualTerminals2: require('../assets/img/hms-laptopandcard.jpg'),
    FreePaymentProcessing1: require('../assets/img/Business-Loans.jpg'),
    FreePaymentProcessing2: require('../assets/img/contactless-card-payment-74484201-1.jpg'),
    FreePaymentProcessing3: require('../assets/img/Car-Rental-GPS-2.jpg'),
    CreditCardMachines1: require('../assets/img/a920_-_1_1024x1024.png'),
    CreditCardMachines2: require('../assets/img/201808221023242086-600x600-1.jpg'),
    CreditCardMachines3: require('../assets/img/VX520_1_med.jpg'),
    CreditCardMachines4: require('../assets/img/iCT250.jpg'),
    CreditCardMachines5: require('../assets/img/Ingenico-iCT220-Image-285x300-1.png'),
    CreditCardMachines6: require('../assets/img/Dejavoo-Z8-768x728-1.jpg'),
    CreditCardMachines7: require('../assets/img/Dejavoo-Z9.jpg'),
    CreditCardMachines8: require('../assets/img/IWL-250.jpg'),
    CreditCardMachines9: require('../assets/img/mobileHomeHeroSwift.png'),
    CreditCardMachines10: require('../assets/img/vital-mobile-c3-card-reader.png'),
    CreditCardMachines11: require('../assets/img/vital-mobile-c4-card-reader.png'),
    CreditCardMachines12: require('../assets/img/Rambler-3.0_product-image.png'),
    CreditCardMachines13: require('../assets/img/Verifone-vx805.jpg'),
    CreditCardMachines14: require('../assets/img/ipp310.jpg'),
    CreditCardMachines15: require('../assets/img/ingenico_ipp320.jpg'),
    CreditCardMachines16: require('../assets/img/Pax_s300_1024x1024.jpg'),
    CreditCardMachines17: require('../assets/img/dejavoo-hardware-pinpad-terminals-Z3-500x500-1.jpg'),
    SalesSystem1: require('../assets/img/the-man-processing-credit-card-transaction-with-pos-terminal-121237867.jpg'),
    SalesSystem2: require('../assets/img/Clover-Family.png'),
    SalesSystem3: require('../assets/img/Vital-product-line-SR19-5R1-768x412-1.jpg'),
    SalesSystem4: require('../assets/img/mpop-1.png'),
    SalesSystem5: require('../assets/img/Bonsai-Express-Stations-SR17-8R1-768x609-1.jpg'),
    CloverPOS1: require('../assets/img/clover-pos.png'),
    CloverPOS2: require('../assets/img/Clover-Mini-768x422-1.jpg'),
    CloverPOS3: require('../assets/img/Clover-Flex-POS-2.jpg'),
    CloverPOS4: require('../assets/img/Screen-Shot-2019-06-19-at-2.32.04-PM.png'),
    CloverPOS5: require('../assets/img/Payment-Processing-For-Merchants.jpg'),
    VitalPOS1: require('../assets/img/website_banner_Vital_POS_options.jpg'),
    VitalPOS2: require('../assets/img/vital-select-SR19-5R1.jpg'),
    VitalPOS3: require('../assets/img/vital-select-x8.jpg'),
    BonsaiPoint1: require('../assets/img/Bonsai-in-restaurant-SR17-8R6.jpg'),
    BonsaiPoint2: require('../assets/img/Bonsai-Isometric-Illustration_SR17-9R2.jpg'),
    BonsaiPoint3: require('../assets/img/Bonsai-POS-with-Credit-card-machine-SR17-8R1.png'),
    BonsaiPoint4: require('../assets/img/POS-Bonsai-Sales-Tools-Graphic-SR17-8R2.png'),
    BonsaiPoint5: require('../assets/img/Bonsai-On-Phones-Graphic-with-Chart-Lines.png'),
    BonsaiPoint6: require('../assets/img/Bonsai-POS-Logo-SR17-5R1.png'),
    BonsaiPoint7: require('../assets/img/Bonsai-Tablet-point-of-sale-restaurant-updated-items-SR17-8R2.jpg'),
    GiftCards1: require('../assets/img/Gift-Cards-Loyalty-Program.jpg'),
    GiftCards2: require('../assets/img/Loyalty-Program.jpg'),
    MerchantCash1: require('../assets/img/Small-Business-Cash-Advance.jpg'),
    MerchantCash2: require('../assets/img/paying-for-organic-food-with-credit-card-EEMXDU5.jpg'),
    MerchantCash3: require('../assets/img/pretty-customer-making-a-mobile-payment-56793048-1.jpg'),
    ApplyMerchantCash1: require('../assets/img/Cash-advance-form-top-banner.jpg'),
    ApplyMerchantCash2: require('../assets/img/Money-Background.jpg'),
    SNAP1: require('../assets/img/contactless-card-payment-74484201-825x340-1.jpg'),
    SNAP2: require('../assets/img/SNAP-logo-for-EBT.jpeg'),
    SNAP3: require('../assets/img/How-To-Accept-EBT-1.jpg'),
    SNAP4: require('../assets/img/paying-for-organic-food-with-credit-card-EEMXDU5 (1).jpg'),
    SNAP5: require('../assets/img/Person-Calling.jpg'),
    SNAP6: require('../assets/img/EBT-03.png'),
    NoCostAccount1: require('../assets/img/Provide-Cash-Discounts-To-Customers.jpg'),
    NoCostAccount2: require('../assets/img/Paying-With-Cash-Discount.jpg'),
    SmallTicket1: require('../assets/img/Happy-Person.jpg'),
    SmallTicket2: require('../assets/img/Small-Ticket-Pricing.jpg'),
    BrenchProtection: require('../assets/img/Protection-Against-A-Data-Breach.jpg'),
    IOSAgent1: require('../assets/img/student-849825_640-1.jpg'),
    IOSAgent2: require('../assets/img/Partner-Portal-graphic-SR19-4R1-panorama.jpg'),
    IOSAgent3: require('../assets/img/Partner-Portal-graphic-Get-paid-on-time-SR19-4R1-panorama.jpg'),
    IOSAgent4: require('../assets/img/Partner-Portal-graphic-Accurate-Residuals-SR19-4R1-panorama.jpg'),
    IOSAgent5: require('../assets/img/Partner-Portal-graphic-dedicated-account-manager-SR19-4R1-panorama.jpg'),
    IOSAgent6: require('../assets/img/Independent-Sales-Image.png'),
    IOSAgent7: require('../assets/img/website_banner_agent_program-1.jpg'),
    ProgramOverview1: require('../assets/img/singlehop.hostmerchantservices.jpeg'),
    ProgramOverview2: require('../assets/img/imsmb.hostmerchantservices.jpeg'),
    ProgramOverview3: require('../assets/img/gearhost.hostmerchantservices.jpeg'),
    ProgramOverview4: require('../assets/img/EdgeWebHosting-2.gif'),
    ProgramOverview5: require('../assets/img/HostMySiteLogo.png'),
    ProgramOverview6: require('../assets/img/vexxhost-feature.png'),
    ProgramOverview7: require('../assets/img/servint-logo.png'),
    ProgramOverview8: require('../assets/img/cha-splash02.png'),
    ProgramOverview9: require('../assets/img/iqcomputing_logo.png'),
    ProgramOverview10: require('../assets/img/techforum-logo.png'),
    ProgramFAQ: require('../assets/img/Host-Merchant-Services-Review.jpg'),
    UsagePermissions: require('../assets/img/Host-Merchant-Services-Review.jpg'),
    About1: require('../assets/img/Restaurant-Block-Lightened-25percent.jpg'),
    About2: require('../assets/img/Lou-2-hms.png'),
    Contact1: require('../assets/img/Why-Choose-HMS-Banner-2.jpg'),
    Contact2: require('../assets/img/HMS_Locations_map_SR17-5R2.jpg'),



}